allNotes = {
    'C':
        [
            { midinote: 24, notename: "c/1", position: { treble: { y: 43 } }, accidental: null },
            { midinote: 25, notename: "c#/1", position: { treble: { y: 43 } }, accidental: "#" },
            { midinote: 26, notename: "d/1", position: { treble: { y: 42 } }, accidental: null },
            { midinote: 27, notename: "d#/1", position: { treble: { y: 42 } }, accidental: "#" },
            { midinote: 28, notename: "e/1", position: { treble: { y: 41 } }, accidental: null },
            { midinote: 29, notename: "f/1", position: { treble: { y: 40 } }, accidental: null },
            { midinote: 30, notename: "f#/1", position: { treble: { y: 40 } }, accidental: "#" },
            { midinote: 31, notename: "g/1", position: { treble: { y: 39 } }, accidental: null },
            { midinote: 32, notename: "g#/1", position: { treble: { y: 39 } }, accidental: "#" },
            { midinote: 33, notename: "a/1", position: { treble: { y: 38 } }, accidental: null },
            { midinote: 34, notename: "a#/1", position: { treble: { y: 38 } }, accidental: "#" },
            { midinote: 35, notename: "b/1", position: { treble: { y: 37 } }, accidental: null },
        
            { midinote: 36, notename: "c/2", position: { treble: { y: 36 } }, accidental: null },
            { midinote: 37, notename: "c#/2", position: { treble: { y: 36 } }, accidental: "#" },
            { midinote: 38, notename: "d/2", position: { treble: { y: 35 } }, accidental: null },
            { midinote: 39, notename: "d#/2", position: { treble: { y: 35 } }, accidental: "#" },
            { midinote: 40, notename: "e/2", position: { treble: { y: 34 } }, accidental: null },
            { midinote: 41, notename: "f/2", position: { treble: { y: 33 } }, accidental: null },
            { midinote: 42, notename: "f#/2", position: { treble: { y: 33 } }, accidental: "#" },
            { midinote: 43, notename: "g/2", position: { treble: { y: 32 } }, accidental: null },
            { midinote: 44, notename: "g#/2", position: { treble: { y: 32 } }, accidental: "#" },
            { midinote: 45, notename: "a/2", position: { treble: { y: 31 } }, accidental: null },
            { midinote: 46, notename: "a#/2", position: { treble: { y: 31 } }, accidental: "#" },
            { midinote: 47, notename: "b/2", position: { treble: { y: 30 } }, accidental: null },
        
            { midinote: 48, notename: "c/3", position: { treble: { y: 29 } }, accidental: null },
            { midinote: 49, notename: "c#/3", position: { treble: { y: 29 } }, accidental: "#" },
            { midinote: 50, notename: "d/3", position: { treble: { y: 28 } }, accidental: null },
            { midinote: 51, notename: "d#/3", position: { treble: { y: 28 } }, accidental: "#" },
            { midinote: 52, notename: "e/3", position: { treble: { y: 27 } }, accidental: null },
            { midinote: 53, notename: "f/3", position: { treble: { y: 26 } }, accidental: null },
            { midinote: 54, notename: "f#/3", position: { treble: { y: 26 } }, accidental: "#" },
            { midinote: 55, notename: "g/3", position: { treble: { y: 25 } }, accidental: null },
            { midinote: 56, notename: "g#/3", position: { treble: { y: 25 } }, accidental: "#" },
            { midinote: 57, notename: "a/3", position: { treble: { y: 24 } }, accidental: null },
            { midinote: 58, notename: "a#/3", position: { treble: { y: 24 } }, accidental: "#" },
            { midinote: 59, notename: "b/3", position: { treble: { y: 23 } }, accidental: null },
        
            { midinote: 60, notename: "c/4", position: { treble: { y: 22 } }, accidental: null },
            { midinote: 61, notename: "c#/4", position: { treble: { y: 22 } }, accidental: "#" },
            { midinote: 62, notename: "d/4", position: { treble: { y: 21 } }, accidental: null },
            { midinote: 63, notename: "d#/4", position: { treble: { y: 21 } }, accidental: "#" },
            { midinote: 64, notename: "e/4", position: { treble: { y: 20 } }, accidental: null },
            { midinote: 65, notename: "f/4", position: { treble: { y: 19 } }, accidental: null },
            { midinote: 66, notename: "f#/4", position: { treble: { y: 19 } }, accidental: "#" },
            { midinote: 67, notename: "g/4", position: { treble: { y: 18 } }, accidental: null },
            { midinote: 68, notename: "g#/4", position: { treble: { y: 18 } }, accidental: "#" },
            { midinote: 69, notename: "a/4", position: { treble: { y: 17 } }, accidental: null },
            { midinote: 70, notename: "a#/4", position: { treble: { y: 17 } }, accidental: "#" },
            { midinote: 71, notename: "b/4", position: { treble: { y: 16 } }, accidental: null },
            
            { midinote: 72, notename: "c/5", position: { treble: { y: 15 } }, accidental: null },
            { midinote: 73, notename: "c#/5", position: { treble: { y: 15 } }, accidental: "#" },
            { midinote: 74, notename: "d/5", position: { treble: { y: 14 } }, accidental: null },
            { midinote: 75, notename: "d#/5", position: { treble: { y: 14 } }, accidental: "#" },
            { midinote: 76, notename: "e/5", position: { treble: { y: 13 } }, accidental: null },
            { midinote: 77, notename: "f/5", position: { treble: { y: 12 } }, accidental: null },
            { midinote: 78, notename: "f#/5", position: { treble: { y: 12 } }, accidental: "#" },
            { midinote: 79, notename: "g/5", position: { treble: { y: 11 } }, accidental: null },
            { midinote: 80, notename: "g#/5", position: { treble: { y: 11 } }, accidental: "#" },
            { midinote: 81, notename: "a/5", position: { treble: { y: 10 } }, accidental: null },
            { midinote: 82, notename: "a#/5", position: { treble: { y: 10 } }, accidental: "#" },
            { midinote: 83, notename: "b/5", position: { treble: { y: 9 } }, accidental: null },
            
            { midinote: 84, notename: "c/6", position: { treble: { y: 8 } }, accidental: null },
            { midinote: 85, notename: "c#/6", position: { treble: { y: 8 } }, accidental: "#" },
            { midinote: 86, notename: "d/6", position: { treble: { y: 7 } }, accidental: null },
            { midinote: 87, notename: "d#/6", position: { treble: { y: 7 } }, accidental: "#" },
            { midinote: 88, notename: "e/6", position: { treble: { y: 6 } }, accidental: null },
            { midinote: 89, notename: "f/6", position: { treble: { y: 5 } }, accidental: null },
            { midinote: 90, notename: "f#/6", position: { treble: { y: 5 } }, accidental: "#" },
            { midinote: 91, notename: "g/6", position: { treble: { y: 4 } }, accidental: null },
            { midinote: 92, notename: "g#/6", position: { treble: { y: 4 } }, accidental: "#" },
            { midinote: 93, notename: "a/6", position: { treble: { y: 3 } }, accidental: null },
            { midinote: 94, notename: "a#/6", position: { treble: { y: 3 } }, accidental: "#" },
            { midinote: 95, notename: "b/6", position: { treble: { y: 2 } }, accidental: null },
            
            { midinote: 96, notename: "c/7", position: { treble: { y: 1 } }, accidental: null },
        ],
    'Gb':
        [
            { midinote: 24, notename: "c/1", position: { treble: { y: 43 } }, accidental: "n" },
            { midinote: 25, notename: "db/1", position: { treble: { y: 42 } }, accidental: null },
            { midinote: 26, notename: "d/1", position: { treble: { y: 42 } }, accidental: "n" },
            { midinote: 27, notename: "eb/1", position: { treble: { y: 41 } }, accidental: null },
            { midinote: 28, notename: "e/1", position: { treble: { y: 41 } }, accidental: "n" },
            { midinote: 29, notename: "f/1", position: { treble: { y: 40 } }, accidental: null },
            { midinote: 30, notename: "gb/1", position: { treble: { y: 39 } }, accidental: null },
            { midinote: 31, notename: "g/1", position: { treble: { y: 39 } }, accidental: "n" },
            { midinote: 32, notename: "ab/1", position: { treble: { y: 38 } }, accidental: null },
            { midinote: 33, notename: "a/1", position: { treble: { y: 38 } }, accidental: "n" },
            { midinote: 34, notename: "bb/1", position: { treble: { y: 37 } }, accidental: null },
            { midinote: 35, notename: "cb/2", position: { treble: { y: 26 } }, accidental: null },
            
            { midinote: 36, notename: "c/2", position: { treble: { y: 36 } }, accidental: "n" },
            { midinote: 37, notename: "db/2", position: { treble: { y: 35 } }, accidental: null },
            { midinote: 38, notename: "d/2", position: { treble: { y: 35 } }, accidental: "n" },
            { midinote: 39, notename: "eb/2", position: { treble: { y: 34 } }, accidental: null },
            { midinote: 40, notename: "e/2", position: { treble: { y: 34 } }, accidental: "n" },
            { midinote: 41, notename: "f/2", position: { treble: { y: 33 } }, accidental: null },
            { midinote: 42, notename: "gb/2", position: { treble: { y: 32 } }, accidental: null },
            { midinote: 43, notename: "g/2", position: { treble: { y: 32 } }, accidental: "n" },
            { midinote: 44, notename: "ab/2", position: { treble: { y: 31 } }, accidental: null },
            { midinote: 45, notename: "a/2", position: { treble: { y: 31 } }, accidental: "n" },
            { midinote: 46, notename: "bb/2", position: { treble: { y: 30 } }, accidental: null },
            { midinote: 47, notename: "cb/3", position: { treble: { y: 29 } }, accidental: null },
        
            { midinote: 48, notename: "c/3", position: { treble: { y: 29 } }, accidental: "n" },
            { midinote: 49, notename: "db/3", position: { treble: { y: 28 } }, accidental: null },
            { midinote: 50, notename: "d/3", position: { treble: { y: 28 } }, accidental: "n" },
            { midinote: 51, notename: "eb/3", position: { treble: { y: 27 } }, accidental: null },
            { midinote: 52, notename: "e/3", position: { treble: { y: 27 } }, accidental: "n" },
            { midinote: 53, notename: "f/3", position: { treble: { y: 26 } }, accidental: null },
            { midinote: 54, notename: "gb/3", position: { treble: { y: 25 } }, accidental: null },
            { midinote: 55, notename: "g/3", position: { treble: { y: 25 } }, accidental: "n" },
            { midinote: 56, notename: "ab/3", position: { treble: { y: 24 } }, accidental: null },
            { midinote: 57, notename: "a/3", position: { treble: { y: 24 } }, accidental: "n" },
            { midinote: 58, notename: "bb/3", position: { treble: { y: 23 } }, accidental: null },
            { midinote: 59, notename: "cb/4", position: { treble: { y: 22 } }, accidental: null },
            
            { midinote: 60, notename: "c/4", position: { treble: { y: 22 } }, accidental: "n" },
            { midinote: 61, notename: "db/4", position: { treble: { y: 21 } }, accidental: null },
            { midinote: 62, notename: "d/4", position: { treble: { y: 21 } }, accidental: "n" },
            { midinote: 63, notename: "eb/4", position: { treble: { y: 20 } }, accidental: null },
            { midinote: 64, notename: "e/4", position: { treble: { y: 20 } }, accidental: "n" },
            { midinote: 65, notename: "f/4", position: { treble: { y: 19 } }, accidental: null },
            { midinote: 66, notename: "gb/4", position: { treble: { y: 18 } }, accidental: null },
            { midinote: 67, notename: "g/4", position: { treble: { y: 18 } }, accidental: "n" },
            { midinote: 68, notename: "ab/4", position: { treble: { y: 17 } }, accidental: null },
            { midinote: 69, notename: "a/4", position: { treble: { y: 17 } }, accidental: "n" },
            { midinote: 70, notename: "bb/4", position: { treble: { y: 16 } }, accidental: null },
            { midinote: 71, notename: "cb/5", position: { treble: { y: 15 } }, accidental: null },
            
            { midinote: 72, notename: "c/5", position: { treble: { y: 15 } }, accidental: "n" },
            { midinote: 73, notename: "db/5", position: { treble: { y: 14 } }, accidental: null },
            { midinote: 74, notename: "d/5", position: { treble: { y: 14 } }, accidental: "n" },
            { midinote: 75, notename: "eb/5", position: { treble: { y: 13 } }, accidental: null },
            { midinote: 76, notename: "e/5", position: { treble: { y: 13 } }, accidental: "n" },
            { midinote: 77, notename: "f/5", position: { treble: { y: 12 } }, accidental: null },
            { midinote: 78, notename: "gb/5", position: { treble: { y: 11 } }, accidental: null },
            { midinote: 79, notename: "g/5", position: { treble: { y: 11 } }, accidental: "n" },
            { midinote: 80, notename: "ab/5", position: { treble: { y: 10 } }, accidental: null },
            { midinote: 81, notename: "a/5", position: { treble: { y: 10 } }, accidental: "n" },
            { midinote: 82, notename: "bb/5", position: { treble: { y: 9 } }, accidental: null },
            { midinote: 83, notename: "cb/6", position: { treble: { y: 8 } }, accidental: null },
            
            { midinote: 84, notename: "c/6", position: { treble: { y: 8 } }, accidental: "n" },
            { midinote: 85, notename: "db/6", position: { treble: { y: 7 } }, accidental: null },
            { midinote: 86, notename: "d/6", position: { treble: { y: 7 } }, accidental: "n" },
            { midinote: 87, notename: "eb/6", position: { treble: { y: 6 } }, accidental: null },
            { midinote: 88, notename: "e/6", position: { treble: { y: 6 } }, accidental: "n" },
            { midinote: 89, notename: "f/6", position: { treble: { y: 5 } }, accidental: null },
            { midinote: 90, notename: "gb/6", position: { treble: { y: 4 } }, accidental: null },
            { midinote: 91, notename: "g/6", position: { treble: { y: 4 } }, accidental: "n" },
            { midinote: 92, notename: "ab/6", position: { treble: { y: 3 } }, accidental: null },
            { midinote: 93, notename: "a/6", position: { treble: { y: 3 } }, accidental: "n" },
            { midinote: 94, notename: "bb/6", position: { treble: { y: 2 } }, accidental: null },
            { midinote: 95, notename: "cb/7", position: { treble: { y: 1 } }, accidental: null },
            
            { midinote: 96, notename: "c/7", position: { treble: { y: 1 } }, accidental: "n" }
        ]
};
